AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  solace-risk-data

  Sample SAM Template for solace-risk-data

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    AutoPublishAlias: live
    Tracing: Active
    Environment:
      Variables:
        DEAD_LETTER_TOPIC: arn:aws:sns:us-west-2:151427405638:RiskDataDeadLetterQueue
        DATA_BUCKET: risk-data.solace.fi.data
    DeadLetterQueue:
      Type: SNS
      TargetArn: arn:aws:sns:us-west-2:151427405638:RiskDataDeadLetterQueue
  Api:
    Cors:
      AllowMethods: "'OPTIONS,GET,POST,PUT,DELETE'"
      AllowHeaders: "'Content-Type'"
      AllowOrigin: "'*'"

Resources:
  # Rest API
  RestApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: SolaceRiskDataApi
      Domain:
        DomainName: risk-data.solace.fi
        CertificateArn: arn:aws:acm:us-west-2:151427405638:certificate/55b18704-e0db-4ce8-b070-43fc8b0c919d
        Route53:
          HostedZoneId: Z0480029MZJJGNMS3NEJ
      StageName: prod
      TracingEnabled: true
  OptionsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SolaceRiskDataOptionsFunction
      Handler: api/options.handler
      Runtime: python3.8
      MemorySize: 128
      Timeout: 3
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /
            Method: options
            RestApiId: !Ref RestApi
  FaviconFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SolaceRiskDataFaviconFunction
      Handler: api/favicon/get.handler
      Runtime: python3.8
      MemorySize: 128
      Timeout: 3
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /favicon.ico
            Method: get
            RestApiId: !Ref RestApi
  GetBalancesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SolaceRiskDataGetBalancesFunction
      Handler: api/balances/get.handler
      Runtime: python3.8
      MemorySize: 128
      Timeout: 600
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /balances
            Method: post
            RestApiId: !Ref RestApi
  TrackBalancesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SolaceRiskDataTrackBalancesFunction
      Handler: api/balances/tracker.handler
      Runtime: python3.8
      MemorySize: 512
      Timeout: 900
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: rate(2 minutes)
  GetScoresFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SolaceRiskDataGetScoresFunction
      Handler: api/scores/get.handler
      Runtime: python3.8
      MemorySize: 128
      Timeout: 600
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /scores
            Method: post
            RestApiId: !Ref RestApi
  GetSeriesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SolaceRiskDataGetSeriesFunction
      Handler: api/series/get.handler
      Runtime: python3.8
      MemorySize: 128
      Timeout: 600
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /series
            Method: get
            RestApiId: !Ref RestApi
  SoteriaScoreTrackerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SolaceRiskDataTrackScoresFunction
      Handler: api/tracks/soteria_rate_tracker.main
      Runtime: python3.8
      MemorySize: 1024
      Timeout: 900
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: rate(60 minutes)
  GetSoteriaScoreTracksFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SolaceRiskDataGetSoteriaScoreTracksFunction
      Handler: api/tracks/get.handler
      Runtime: python3.8
      MemorySize: 128
      Timeout: 600
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /tracks
            Method: get
            RestApiId: !Ref RestApi
  SoteriaBillingFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SolaceRiskDataSoteriaBillingFunction
      Handler: api/billing/soteria_billing_calculator.main
      Runtime: python3.8
      MemorySize: 1024
      Timeout: 600
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: cron(00 17 ? * FRI *)
  SoteriaBillingCollectorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SolaceRiskDataSoteriaBillingCollector
      Handler: api/billing/soteria_billing_collector.main
      Runtime: python3.8
      MemorySize: 1024
      Timeout: 600
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: cron(00 18 ? * FRI *)
  GetSoteriaBillingsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SolaceRiskDataGetSoteriaBillingsFunction
      Handler: api/billing/handler.get_all_billings_handler
      Runtime: python3.8
      MemorySize: 128
      Timeout: 600
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /billings/all
            Method: get
            RestApiId: !Ref RestApi
  GetSoteriaBillingsByAccountFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SolaceRiskDataGetSoteriaBillingsByAccountFunction
      Handler: api/billing/handler.get_billings_by_account_handler
      Runtime: python3.8
      MemorySize: 128
      Timeout: 600
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /billings
            Method: get
            RestApiId: !Ref RestApi
  GetSoteriaUnpaidBillingsByAccountFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SolaceRiskDataGetSoteriaUnpaidBillingsByAccountFunction
      Handler: api/billing/handler.get_unpaid_billings_by_account_handler
      Runtime: python3.8
      MemorySize: 128
      Timeout: 600
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /billings/unpaid
            Method: get
            RestApiId: !Ref RestApi
  GetSoteriaPaidBillingsByAccountFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SolaceRiskDataGetSoteriaPaidBillingsByAccountFunction
      Handler: api/billing/handler.get_paid_billings_by_account_handler
      Runtime: python3.8
      MemorySize: 128
      Timeout: 600
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /billings/paid
            Method: get
            RestApiId: !Ref RestApi
  GetSoteriaPremiumByAccountFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SolaceRiskDataGetSoteriaPremiumByAccountFunction
      Handler: api/billing/handler.get_premium_amount_handler
      Runtime: python3.8
      MemorySize: 128
      Timeout: 600
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /premium
            Method: get
            RestApiId: !Ref RestApi
  GetPriceHistoryFunction:
      Type: AWS::Serverless::Function
      Properties:
        FunctionName: SolaceRiskDataGetPriceHistoryFunction
        Handler: api/pricehistory/get.handler
        Runtime: python3.8
        MemorySize: 128
        Timeout: 600
        Role: !GetAtt LambdaExecutionRole.Arn
        Events:
          GetEvent:
            Type: Api
            Properties:
              Path: /price-history
              Method: get
              RestApiId: !Ref RestApi
  #GetVolatilityFunction:
  #    Type: AWS::Serverless::Function
  #    Properties:
  #      FunctionName: SolaceRiskDataGetVolatilityFunction
  #      Handler: api/volatility/get.handler
  #      Runtime: python3.8
  #      MemorySize: 128
  #      Timeout: 600
  #      Role: !GetAtt LambdaExecutionRole.Arn
  #      Events:
  #        GetEvent:
  #          Type: Api
  #          Properties:
  #            Path: /volatility
  #            Method: get
  #            RestApiId: !Ref RestApi
  # Data Bucket
  DataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: risk-data.solace.fi.data
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      CorsConfiguration:
        CorsRules:
          - AllowedMethods:
              - HEAD
              - GET
            AllowedOrigins:
              - "*"
            AllowedHeaders:
              - "*"
  # SNS Dead Letter Topic
  DeadLetterTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: Solace Risk Data Dead Letter Queue
      TopicName: RiskDataDeadLetterQueue
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: SolaceRiskDataLambdaExecutionRole
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: [lambda.amazonaws.com]
            Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      Policies:
        - PolicyName: SolaceRiskDataLambdaExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "sns:Publish"
                Resource: "arn:aws:sns:us-west-2:151427405638:RiskDataDeadLetterQueue"
              - Effect: Allow
                Action:
                  - "s3:GetObject"
                  - "s3:DeleteObject"
                  - "s3:ListBucket"
                  - "s3:ListObjectsV2"
                  - "s3:PutObject"
                  - "s3:ReplicateObject"
                  - "s3:RestoreObject"
                Resource: "arn:aws:s3:::risk-data.solace.fi.data/*"
